version: '3'

services:
  # mysql
  db:
    image: mysql # nama image yang akan di pakai connect database 
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: my_secret_password
    networks:
      - mysql-phpmyadmin

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8086:80" # port lokal:port container
    environment:
      - PHP_UPLOAD_MAX_FILESIZE=300M
      - PHP_POST_MAX_SIZE=300M
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  db_data:
